### ISSUE TITLE
Docker container error

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/coral-pi-rest-server#20]
I am getting:
```
(base) robin@robins-ubuntu:~/Github/coral-pi-rest-server$ sudo docker run -p 5000:5000 --device /dev/bus/usb:/dev/bus/usb   coral:latest
Traceback (most recent call last):
  File "coral-app.py", line 122, in <module>
    load_model(args.model, args.labels)
  File "coral-app.py", line 48, in load_model
    engine = DetectionEngine(model_file)
  File "/usr/local/lib/python3.6/site-packages/edgetpu/detection/engine.py", line 55, in __init__
    super().__init__(model_path)
  File "/usr/local/lib/python3.6/site-packages/edgetpu/swig/edgetpu_cpp_wrapper.py", line 300, in __init__
    this = _edgetpu_cpp_wrapper.new_BasicEngine(*args)
RuntimeError: Failed to allocate tensors.
```

Any ideas @lmamakos ?

**Comment by lmamakos** [comment]
The models should have been installed in the /models directory inside the container.  Can you check and see if they ended up there?  Something like:

```bash
louie@hass[389] $ docker run -it coral bash
root@1691373f3111:/usr/src/app# ls -l /models
total 6277
-rw-r--r-- 1 root root     930 Jun 15 04:49 coco_labels.txt
-rw-r--r-- 1 root root 6948536 Jun 15 04:49 mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite
root@1691373f3111:/usr/src/app#
```

The other possibility is that you'll get this error if the edgetpu library isn't able to find the coral USB device.  For example, if you run the same `docker` command, and leave out the `--device` mapping option, I think you'll get the same error.

**Comment by lmamakos** [comment]
Also, if there is a noticeable delay, like 5 or 10 seconds before you get this error, then almost certainly it's not able to access the USB device.  

I'm trying to recall if I had to do anything special/weird to allow access to the USB device.  On the host, my permissions look like this:

```bash
louie@hass[394] $ ls -lR /dev/bus/usb
/dev/bus/usb:
total 0
drwxr-xr-x 2 root root 80 Jul  4 01:24 001/
drwxr-xr-x 2 root root 80 Jun 29 23:33 002/

/dev/bus/usb/001:
total 0
crw-rw-r-- 1 root root 189, 0 Jun 29 23:33 001
crw-rw-r-- 1 root root 189, 1 Jun 29 23:33 002

/dev/bus/usb/002:
total 0
crw-rw-r-- 1 root root    189, 128 Jun 29 23:33 001
crw-rw---- 1 root plugdev 189, 130 Jun 29 23:33 003
louie@hass[395] $
```
Ah, I noticed that the edgetpu installer has a `99-edgetpu-accelerator.rules` file that gets installed to set some access permissions..

```
SUBSYSTEM=="usb",ATTRS{idVendor}=="1a6e",GROUP="plugdev"
SUBSYSTEM=="usb",ATTRS{idVendor}=="18d1",GROUP="plugdev"
```

This must have been installed at some point before I was using docker, and possibly arranges for the group ownership to get set when the coral USB device is inserted.

**Comment by robmarkcole** [comment]
So I ran the server in regular mode (i.e. not docker), worked fine. Tried the docker again, and now it works fine. I have restarted the machine and docker ran first time. Will keep this issue open for now in case it resurfaces. Thanks for your help!
