### ISSUE TITLE
issue with the docker

### ISSUE THREAD

**Issue by lele344** [robmarkcole/coral-pi-rest-server#27]
Hi robmarcole,
I tried to use your docker, but when I start it I receive the following errors:

> Traceback (most recent call last):
>   File "coral-app.py", line 84, in <module>
>     engine = DetectionEngine(MODEL_FILE)
>   File "/usr/local/lib/python3.6/site-packages/edgetpu/detection/engine.py", line 72, in __init__
>     super().__init__(model_path)
>   File "/usr/local/lib/python3.6/site-packages/edgetpu/basic/basic_engine.py", line 40, in __init__
>     self._engine = BasicEnginePythonWrapper.CreateFromFile(model_path)
> RuntimeError: Could not open '/home/robin/edgetpu/all_models/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite'.

please could you help me to understand how can I fix this issue on my debian?
Thank you

**Comment by robmarkcole** [comment]
This is https://github.com/robmarkcole/coral-pi-rest-server/issues/1 We need to address that ASAP. For now I you will need to edit the paths
