### ISSUE TITLE
USB Transfer Error

### ISSUE THREAD

**Issue by rob26r** [robmarkcole/coral-pi-rest-server#52]
Hi - Im getting the error message that you noted in your troubleshooting.  It says to reflash the SD card.  What does reflash the SC card mean?  

Q: I get the error: HandleQueuedBulkIn transfer in failed. Not found: USB transfer error 5 [LibUsbDataInCallback] A: I reflashed the SD card and tried again with success

Thanks.

**Comment by robmarkcole** [comment]
The SD card with the OS on it

**Comment by rob26r** [comment]
sorry still don't understand. I know what the SD card is.  What does reflash mean?

**Comment by robmarkcole** [comment]
The process of transfering the disk image (e.g. using Etcher) to the SD card is called flashing. Reflashing is to repeat the process.
