### ISSUE TITLE
Bounding boxes with very low confidence.

### ISSUE THREAD

**Issue by roofuskit** [robmarkcole/coral-pi-rest-server#58]
I'm getting a lot of bounding boxes, a LOT. Many of them are often very low confidence. Is there any way to correct this?
![photo5064402415427627057](https://user-images.githubusercontent.com/566975/82818676-b17e8b00-9e64-11ea-9a12-00510930cf17.jpg)

![photo5064402415427627051](https://user-images.githubusercontent.com/566975/82818678-b17e8b00-9e64-11ea-93ea-26df567aa974.jpg)

![photo5060054018738464947](https://user-images.githubusercontent.com/566975/82818685-b2172180-9e64-11ea-9662-3a66d65e3587.jpg)

![photo5060054018738464946](https://user-images.githubusercontent.com/566975/82818691-b2afb800-9e64-11ea-8ba5-008d20f5ac89.jpg)

**Comment by robmarkcole** [comment]
You can filter them on confidence before displaying

**Comment by sstratoti** [comment]
Looking the code in https://github.com/robmarkcole/coral-pi-rest-server/blob/master/coral-app.py on line 56 you set an explicit threshold of 0.4. However we're getting back scores that are below that in the results?

With deepstack, you can set the minimum confidence through the API call
https://docs.deepstack.cc/object-detection/index.html#setting-minimum-confidence

If we're trying to emulate an endpoint, would it be possible to add this in as a parameter in the request? 

Not as familiar with flask, but I could muddle my way through and submit a PR if needed. I think the main issue is that its returning values above the threshold to begin with.

**Comment by robmarkcole** [comment]
Possibly the confidences are in %, so 0.4% is too low. Just a guess, been a long time since I worked on this

**Comment by sstratoti** [comment]
Yup - never hit the comment button in my browser.
 
So like I was saying, I'm having an issue with the bounding boxes similar to #62 - for some reason I don't think they're scaling correctly for me. I think I may be using an older version of pycoral in my docker container...not sure how to check which version. Going to try running it locally first to confirm its still an issue, and then try to figure out the docker container bit.
