### ISSUE TITLE
Bounding boxes incorrect

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/coral-pi-rest-server#62]
After my quick hacking to update to use pycoral the bounding boxes are incorrect - perhaps since the image is resized to (300, 300) before processing?

**Comment by scho0ck** [comment]
Do you have any idea how to fix this I'm currently looking into this as the newer library is much faster. BTW I actually use this on my BlueIris NVR with the offical DeepStack integration and apart from the bounding box issue on the pycoral version it's working fine.

**Comment by robmarkcole** [comment]
Options are: read new docs and find the, or hack it

**Comment by scho0ck** [comment]
FYI

The scaling is fine that's handled by the scale variable however the object was wrong this works fine
```
                            "y_min": int(obj.bbox[1]),
                            "x_min": int(obj.bbox[0]),
                            "y_max": int(obj.bbox[3]),
                            "x_max": int(obj.bbox[2]),
```

**Comment by robmarkcole** [comment]
Excellent, could you make a PR to apply this fix? Thanks

**Comment by robmarkcole** [comment]
fixed
