### ISSUE TITLE
Create a separate branch for legacy code (v1.x)

### ISSUE THREAD

**Issue by grinco** [robmarkcole/coral-pi-rest-server#67]
I've done some changes to your code. See a diff here: https://github.com/robmarkcole/coral-pi-rest-server/compare/v1.0...grinco:v1.0?expand=1

Can you create a v1x branch so I'd merge it into it? I still can't run 2.0 and would like to merge my changes upstream.
Cheers!

**Comment by grinco** [comment]
Any update? I'd like to push some additional fixes to that branch. Cheers.

**Comment by robmarkcole** [comment]
@grinco sorry I dont get notifications from github, dont know why!

Created https://github.com/robmarkcole/coral-pi-rest-server/tree/v1x

**Comment by robmarkcole** [comment]
done
